name: Frontend Test Cypress

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    env:
            VUE_APP_API_URL: "http://127.0.0.1:8080"
            VUE_APP_TITLE: ${{ secrets.VUE_APP_TITLE }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: docker build --tag test-frontend-monashfyp .
      - run: docker run --init -d --name test-frontend-monashfyp -p 8080:4444 test-frontend-monashfyp
      - run: echo "Web app is ready to test and running on http://127.0.0.1:8080"
      - run: echo "testing locally hosted webpage"
      - run: curl http://127.0.0.1:8080
      - uses: cypress-io/github-action@v2
        
        
